use ::line_index::LineIndex;
use ide::{
    Database, FindSymbol, FinishedFile, FunctionId, ImportMembers, ScopeId, Source, Symbol,
    SymbolFlags, SymbolKind, Type, line_index, parse,
};
use lsp_types::{
    Command, CompletionItem, CompletionItemKind, CompletionItemTag, CompletionParams,
    CompletionResponse, CompletionTextEdit, InsertTextFormat, TextEdit,
};
use sq_3_parser::{
    AstNode, KEYWORDS, SyntaxKind, SyntaxNode, TextRange, TextSize,
    ast::{self, IsClassMember},
};
use std::fmt::Write as _;

use crate::conversions;

pub fn handle_completions(db: &Database, params: CompletionParams) -> CompletionResponse {
    let uri = params.text_document_position.text_document.uri;

    let Ok(path) = uri.to_file_path() else {
        return CompletionResponse::Array(Vec::new());
    };

    let Some(file) = db.get_file(&path) else {
        return CompletionResponse::Array(Vec::new());
    };

    let line_idx = line_index(db, file);

    let offset = conversions::test_size(line_idx, params.text_document_position.position);
    let syntax = parse(db, file).syntax();

    let finished_file = FinishedFile::new(db, file);

    let scope = finished_file.scope(offset);
    let trigger_char = params.context.and_then(|c| c.trigger_character);

    CompletionResponse::Array(
        match context_completions(&syntax, offset, trigger_char.as_deref(), &finished_file) {
            // Some(ContextCompletions::Flat) => completions_flat(offset, &finished_file),
            Some(ContextCompletions::Statement) => {
                let mut completions = completions_flat(offset, &finished_file);
                completions.extend(statement_keywords());
                completions
            }
            Some(ContextCompletions::Expression) => {
                let mut completions = completions_flat(offset, &finished_file);
                completions.extend(expression_keywords());
                completions
            }
            Some(ContextCompletions::FromObject { typ, prefix_range }) => {
                completions_from_object(line_idx, offset, &finished_file, scope, typ, prefix_range)
            }
            Some(ContextCompletions::FromQualifiedName { typ }) => {
                completions_from_qualified_name(offset, &finished_file, scope, typ)
            }
            Some(ContextCompletions::FromObjectAsString { typ, replace_range }) => {
                completions_from_object_as_string(
                    line_idx,
                    offset,
                    &finished_file,
                    scope,
                    typ,
                    replace_range,
                )
            }
            Some(ContextCompletions::Root) => completions_root(offset, &finished_file, scope),
            Some(ContextCompletions::AfterLocal | ContextCompletions::Table) => {
                let keywords = [Keyword("function", KeywordPostfix::Space)];
                keywords_to_completion(&keywords)
            }
            Some(ContextCompletions::Class) => {
                let keywords = [
                    Keyword("function", KeywordPostfix::Space),
                    Keyword("constructor", KeywordPostfix::Parentheses),
                    Keyword("static", KeywordPostfix::Space),
                ];
                keywords_to_completion(&keywords)
            }
            Some(ContextCompletions::ClassAfterStatic) => {
                let keywords = [
                    Keyword("function", KeywordPostfix::Space),
                    Keyword("constructor", KeywordPostfix::Parentheses),
                ];
                keywords_to_completion(&keywords)
            }
            Some(ContextCompletions::Switch) => {
                let mut completions = completions_flat(offset, &finished_file);
                completions.extend(statement_keywords());
                let keywords = [
                    Keyword("case", KeywordPostfix::Space),
                    Keyword("default", KeywordPostfix::None),
                ];
                completions.extend(keywords_to_completion(&keywords));
                completions
            }
            Some(ContextCompletions::DocTag { replace_range }) => {
                completion_doc_tag(line_idx, replace_range)
            }
            Some(ContextCompletions::DocType) => completions_doc_type(offset, &finished_file),
            Some(ContextCompletions::DocParamNames { id }) => {
                completions_doc_param_names(id, &finished_file)
            }
            Some(ContextCompletions::DocAutoGenerated { typ, replace_range }) => {
                completion_doc_auto_generated(line_idx, &finished_file, typ, replace_range)
            }
            None => Vec::new(),
        },
    )
}

enum ContextCompletions {
    Statement,
    Expression,
    Root,
    FromQualifiedName { typ: Option<Type> },
    FromObject { typ: Type, prefix_range: TextRange },
    FromObjectAsString { typ: Type, replace_range: TextRange },
    AfterLocal,
    Table,
    Class,
    ClassAfterStatic,
    Switch,
    DocTag { replace_range: Option<TextRange> },
    DocType,
    DocParamNames { id: FunctionId },
    DocAutoGenerated { typ: Type, replace_range: TextRange },
}

fn doc_trigger(trigger_char: Option<&str>) -> bool {
    matches!(trigger_char, Some("@" | "|" | "{" | "*"))
}

fn not_doc_trigger(trigger_char: Option<&str>) -> bool {
    matches!(trigger_char, Some("." | "\""))
}

fn param_tag_name(
    finished_file: &FinishedFile<'_>,
    parent: &SyntaxNode,
) -> Option<ContextCompletions> {
    let Some(parent) = parent.parent() else {
        return Some(ContextCompletions::DocTag {
            replace_range: None,
        });
    };

    if !ast::ParamTag::can_cast(parent.kind()) {
        return Some(ContextCompletions::DocTag {
            replace_range: None,
        });
    }

    let comment = parent.parent()?;
    if !ast::DocComment::can_cast(comment.kind()) {
        return None;
    }
    let range = comment.text_range();
    let symbol = finished_file.doc_to_symbol().get(&range)?;
    let Type::Function(Some(id)) = finished_file.get(*symbol).typ.0 else {
        return None;
    };

    Some(ContextCompletions::DocParamNames { id })
}

#[allow(clippy::too_many_lines)]
fn context_completions(
    syntax: &SyntaxNode,
    offset: TextSize,
    trigger_char: Option<&str>,
    finished_file: &FinishedFile,
) -> Option<ContextCompletions> {
    let Some(mut token) = syntax.token_at_offset(offset).left_biased() else {
        return Some(ContextCompletions::Statement);
    };

    let touching = token.kind() != SyntaxKind::Whitespace;
    if !touching {
        let Some(prev_token) = token.prev_token() else {
            return Some(ContextCompletions::Statement);
        };

        token = prev_token;
    }

    match token.kind() {
        SyntaxKind::LineComment | SyntaxKind::BlockComment => {
            if touching {
                None
            } else {
                Some(ContextCompletions::Statement)
            }
        }
        SyntaxKind::ColonColon => {
            if doc_trigger(trigger_char) {
                return None;
            }

            let parent = token.parent()?;

            // e.g.
            // ::|
            // ::   |
            if ast::RootAccessExpression::can_cast(parent.kind()) {
                return Some(ContextCompletions::Root);
            }

            // e.g.
            // function abc::|
            // function abc::   |
            let part = ast::QualifiedNamePart::cast(parent)?;
            let name = part.name()?;
            let symbol = finished_file
                .range_to_symbol()
                .get(&name.syntax().text_range())?;

            Some(ContextCompletions::FromQualifiedName {
                typ: Some(finished_file.get(*symbol).typ.0),
            })
        }
        SyntaxKind::String => {
            if !touching {
                return Some(ContextCompletions::Expression);
            }

            if trigger_char != Some("\"") {
                return None;
            }

            let expr = token.parent()?;
            if !ast::LiteralExpression::can_cast(expr.kind()) {
                return None;
            }

            let index = expr.parent()?;
            if !ast::Index::can_cast(index.kind()) {
                return None;
            }

            let parent = index.parent()?;
            if let Some(node) = ast::ElementAccessExpression::cast(parent) {
                let Type::String(Some(id)) = finished_file.type_at(token.text_range()) else {
                    return None;
                };

                let typ = finished_file.type_at(node.object()?.syntax().text_range());
                let unquoted_range = finished_file.get(id).unquoted_range;
                let replace_range =
                    TextRange::new(unquoted_range.start(), index.text_range().end());

                Some(ContextCompletions::FromObjectAsString { typ, replace_range })
            } else {
                None
            }
        }
        SyntaxKind::Dot => {
            if doc_trigger(trigger_char) {
                return None;
            }

            let Some(parent) = token.parent() else {
                return Some(ContextCompletions::Statement);
            };

            Some(
                if let Some(node) = ast::MemberAccessExpression::cast(parent) {
                    let typ = finished_file.type_at(node.object()?.syntax().text_range());
                    ContextCompletions::FromObject {
                        typ,
                        prefix_range: token.text_range().cover_offset(offset),
                    }
                } else {
                    ContextCompletions::Statement
                },
            )
        }
        SyntaxKind::FunctionKeyword if !touching => {
            if doc_trigger(trigger_char) {
                return None;
            }

            let parent = token.parent()?;
            // function |
            if ast::FunctionStatement::can_cast(parent.kind()) {
                return Some(ContextCompletions::FromQualifiedName { typ: None });
            }

            // The rest are
            // local function |
            // (method) function |
            // (expression) function |
            // These should not have any completions since we're writing out the name
            None
        }
        SyntaxKind::LocalKeyword if !touching => Some(ContextCompletions::AfterLocal),
        SyntaxKind::StaticKeyword if !touching => Some(ContextCompletions::ClassAfterStatic),
        SyntaxKind::EnumKeyword | SyntaxKind::ConstKeyword if !touching => None,

        SyntaxKind::BaseKeyword
        | SyntaxKind::BreakKeyword
        | SyntaxKind::CaseKeyword
        | SyntaxKind::CatchKeyword
        | SyntaxKind::ClassKeyword
        | SyntaxKind::CloneKeyword
        | SyntaxKind::ConstKeyword
        | SyntaxKind::ContinueKeyword
        | SyntaxKind::DefaultKeyword
        | SyntaxKind::DeleteKeyword
        | SyntaxKind::DoKeyword
        | SyntaxKind::ElseKeyword
        | SyntaxKind::EnumKeyword
        | SyntaxKind::ExtendsKeyword
        | SyntaxKind::FalseKeyword
        | SyntaxKind::ForEachKeyword
        | SyntaxKind::ForKeyword
        | SyntaxKind::FunctionKeyword
        | SyntaxKind::IfKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::LocalKeyword
        | SyntaxKind::NullKeyword
        | SyntaxKind::RawCallKeyword
        | SyntaxKind::ResumeKeyword
        | SyntaxKind::ReturnKeyword
        | SyntaxKind::StaticKeyword
        | SyntaxKind::SwitchKeyword
        | SyntaxKind::ThisKeyword
        | SyntaxKind::ThrowKeyword
        | SyntaxKind::TrueKeyword
        | SyntaxKind::TryKeyword
        | SyntaxKind::TypeOfKeyword
        | SyntaxKind::WhileKeyword
        | SyntaxKind::YieldKeyword
        | SyntaxKind::FileKeyword
        | SyntaxKind::LineKeyword
        | SyntaxKind::Identifier => {
            if !touching {
                return Some(ContextCompletions::Expression);
            }

            if doc_trigger(trigger_char) {
                return None;
            }

            let mut parent = token.parent()?;
            if matches!(parent.kind(), SyntaxKind::Name | SyntaxKind::Error) {
                parent = parent.parent()?;
            }

            // local a = {
            //    fun|
            // }
            if ast::SimpleName::can_cast(parent.kind()) {
                let property = ast::Property::cast(parent.parent()?)?;
                return match property.syntax().parent()?.kind() {
                    SyntaxKind::TableLiteralExpression => Some(ContextCompletions::Table),
                    SyntaxKind::ClassStatement | SyntaxKind::ClassExpression => {
                        if property.static_keyword().is_none() {
                            Some(ContextCompletions::Class)
                        } else {
                            Some(ContextCompletions::ClassAfterStatic)
                        }
                    }
                    _ => None,
                };
            }

            // const b| = 1;
            // local b = {
            //    function ab|
            // }
            if matches!(
                parent.kind(),
                |SyntaxKind::LocalFunctionDeclaration| SyntaxKind::Method
                    | SyntaxKind::Constructor
                    | SyntaxKind::ForeachKey
                    | SyntaxKind::ForeachValue
                    | SyntaxKind::ConstStatement
                    | SyntaxKind::EnumStatement
            ) {
                return None;
            }

            // local a| = 1
            // function abc(a|)
            if let Some(var) = ast::VariableDeclaration::cast(parent.clone()) {
                let local_decl = ast::LocalVariableDeclaration::cast(parent.parent()?)?;
                let first = local_decl.declarations().next()?;
                if first == var {
                    return Some(ContextCompletions::AfterLocal);
                }
                return None;
            }

            // ::  a|
            if ast::RootAccessExpression::can_cast(parent.kind()) {
                return Some(ContextCompletions::Root);
            }

            // function abc::wow::new|
            // function new|
            if let Some(qualified_name) = ast::QualifiedName::cast(parent.clone()) {
                if let Some(last) = qualified_name.parts().last() {
                    let name = last.name()?;
                    let symbol = finished_file
                        .range_to_symbol()
                        .get(&name.syntax().text_range())?;

                    return Some(ContextCompletions::FromQualifiedName {
                        typ: Some(finished_file.get(*symbol).typ.0),
                    });
                }

                return Some(ContextCompletions::FromQualifiedName { typ: None });
            }

            // function abc::wow|::new
            if let Some(part) = ast::QualifiedNamePart::cast(parent.clone()) {
                let qualified_name = ast::QualifiedName::cast(part.syntax().parent()?)?;
                let mut last = None;
                for part in qualified_name.parts() {
                    if part.syntax().text_range().end() < offset {
                        last = Some(part);
                    } else {
                        break;
                    }
                }

                let name = last?.name()?;
                let symbol = finished_file
                    .range_to_symbol()
                    .get(&name.syntax().text_range())?;

                return Some(ContextCompletions::FromQualifiedName {
                    typ: Some(finished_file.get(*symbol).typ.0),
                });
            }

            if ast::ExpressionStatement::can_cast(parent.kind()) {
                if let Some(parent) = parent.parent()
                    && matches!(
                        parent.kind(),
                        //no default clause because no clauses below it make sense?
                        SyntaxKind::SwitchStatement | SyntaxKind::CaseClause // | SyntaxKind::DefaultClause
                    )
                {
                    return Some(ContextCompletions::Switch);
                }
                return Some(ContextCompletions::Statement);
            }

            // Member access also wraps it in 'member' node
            let Some(member_access) = parent.parent() else {
                return Some(ContextCompletions::Statement);
            };

            Some(
                if let Some(node) = ast::MemberAccessExpression::cast(member_access) {
                    let object_range = node.object()?.syntax().text_range();
                    let typ = finished_file.type_at(object_range);
                    let prefix_range = node.dot_token().map_or_else(
                        || TextRange::new(object_range.end(), parent.text_range().start()),
                        |dot| TextRange::new(dot.text_range().start(), parent.text_range().start()),
                    );
                    ContextCompletions::FromObject { typ, prefix_range }
                } else {
                    ContextCompletions::Expression
                },
            )
        }
        SyntaxKind::Comma => {
            if doc_trigger(trigger_char) {
                return None;
            }

            match token.parent()?.kind() {
                SyntaxKind::TableLiteralExpression => Some(ContextCompletions::Table),
                SyntaxKind::ClassStatement | SyntaxKind::ClassExpression => {
                    Some(ContextCompletions::Class)
                }
                SyntaxKind::ParameterList
                | SyntaxKind::LocalVariableDeclaration
                | SyntaxKind::ForEachStatement
                | SyntaxKind::EnumStatement => None,
                _ => Some(ContextCompletions::Expression),
            }
        }
        SyntaxKind::LineFeed | SyntaxKind::Semicolon => {
            if doc_trigger(trigger_char) {
                return None;
            }

            match token.parent()?.kind() {
                SyntaxKind::TableLiteralExpression => Some(ContextCompletions::Table),
                SyntaxKind::ClassStatement | SyntaxKind::ClassExpression => {
                    Some(ContextCompletions::Class)
                }
                //no default clause because no clauses below it make sense?
                SyntaxKind::SwitchStatement | SyntaxKind::CaseClause // | SyntaxKind::DefaultClause
                    => Some(ContextCompletions::Switch),
                SyntaxKind::EnumStatement => None,
                _ => Some(ContextCompletions::Statement),
            }
        }

        SyntaxKind::DocOpenBrace | SyntaxKind::DocPipe => {
            if not_doc_trigger(trigger_char) {
                return None;
            }

            Some(ContextCompletions::DocType)
        }
        SyntaxKind::DocCloseBrace => {
            if not_doc_trigger(trigger_char) {
                return None;
            }

            let Some(parent) = token.parent() else {
                return Some(ContextCompletions::DocTag {
                    replace_range: None,
                });
            };

            if !ast::DocType::can_cast(parent.kind()) {
                return Some(ContextCompletions::DocTag {
                    replace_range: None,
                });
            }

            // e.g.
            // @param {type} |
            param_tag_name(finished_file, &parent)
        }
        SyntaxKind::DocText | SyntaxKind::DocAsterisk => {
            if not_doc_trigger(trigger_char) {
                return None;
            }

            Some(ContextCompletions::DocTag {
                replace_range: None,
            })
        }
        SyntaxKind::DocAt => {
            if not_doc_trigger(trigger_char) {
                return None;
            }

            // e.g
            // @| -> show
            // @  | -> don't show
            if !touching {
                return Some(ContextCompletions::DocTag {
                    replace_range: None,
                });
            }

            Some(ContextCompletions::DocTag {
                replace_range: token
                    .parent()
                    .and_then(ast::DocTagItem::cast)
                    .map(|i| i.syntax().text_range()),
            })
        }
        SyntaxKind::DocIdentifier => {
            if not_doc_trigger(trigger_char) {
                return None;
            }

            let Some(parent) = token.parent() else {
                return Some(ContextCompletions::DocTag {
                    replace_range: None,
                });
            };

            // @param name| -> show names
            // @param name  | -> show tags
            if ast::DocName::can_cast(parent.kind()) {
                if !touching {
                    return Some(ContextCompletions::DocTag {
                        replace_range: None,
                    });
                }

                return param_tag_name(finished_file, &parent);
            }

            if !touching
                && ast::DocTagItem::can_cast(parent.kind())
                && let Some(completions) = param_tag_name(finished_file, &parent)
            {
                return Some(completions);
            }

            if ast::DocTypeName::can_cast(parent.kind()) {
                return Some(ContextCompletions::DocType);
            }

            Some(ContextCompletions::DocTag {
                replace_range: ast::DocTagItem::cast(parent).map(|i| i.syntax().text_range()),
            })
        }
        SyntaxKind::DocAsteriskSlash | SyntaxKind::DocSlashAsteriskAsterisk => {
            if token.kind() == SyntaxKind::DocAsteriskSlash && !touching {
                return Some(ContextCompletions::Statement);
            }

            let Some(parent) = token.parent() else {
                return Some(ContextCompletions::DocTag {
                    replace_range: None,
                });
            };

            if !ast::DocComment::can_cast(parent.kind()) {
                return Some(ContextCompletions::DocTag {
                    replace_range: None,
                });
            }

            let range = parent.text_range();
            let Some(symbol) = finished_file.doc_to_symbol().get(&range) else {
                return Some(ContextCompletions::DocTag {
                    replace_range: None,
                });
            };

            Some(ContextCompletions::DocAutoGenerated {
                typ: finished_file.get(*symbol).typ.0,
                replace_range: range,
            })
        }

        _ => {
            if doc_trigger(trigger_char) {
                return None;
            }

            Some(ContextCompletions::Expression)
        }
    }
}

fn modify_if_function(
    finished_file: &FinishedFile,
    symbol: &Symbol,
    label: &mut String,
    insert_text: &mut Option<String>,
) -> Option<(InsertTextFormat, Command)> {
    // we don't use finished_file.to_function_id since
    // we don't want () autocompletion on classes and such
    let Type::Function(id) = symbol.typ.0 else {
        return None;
    };

    let text = insert_text
        .as_mut()
        .map_or(label.as_str(), |text| text.as_str());

    if let Some(id) = id {
        let func = finished_file.get(id);

        if func.params.is_empty() {
            *insert_text = Some(format!("{text}()"));
            *label = format!("{label}()");
            return None;
        }
    }

    *insert_text = Some(format!("{text}($1)"));
    *label = format!("{label}(…)");
    Some((
        InsertTextFormat::SNIPPET,
        Command {
            title: "Trigger Signature Help".to_owned(),
            command: "editor.action.triggerParameterHints".to_owned(),
            arguments: None,
        },
    ))
}

fn can_use_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };

    if KEYWORDS.contains_key(name) {
        return name == "constructor";
    }

    if !first.is_ascii_alphabetic() && first != '_' {
        return false;
    }

    for char in chars {
        if !char.is_alphanumeric() && char != '_' {
            return false;
        }
    }

    true
}

fn symbol_tags(symbol: &Symbol) -> Option<Vec<CompletionItemTag>> {
    symbol
        .flags
        .contains(SymbolFlags::DEPRECATED)
        .then(|| vec![CompletionItemTag::DEPRECATED])
}

const fn to_completion_kind(symbol: &Symbol) -> CompletionItemKind {
    match symbol.typ.0 {
        Type::Enum(_) => CompletionItemKind::ENUM,
        Type::Function(_) => CompletionItemKind::FUNCTION,
        Type::Class(_) => CompletionItemKind::CLASS,
        _ => match symbol.kind {
            SymbolKind::Local(_) => CompletionItemKind::VARIABLE,
            SymbolKind::Constant => CompletionItemKind::CONSTANT,
            SymbolKind::Property(_) => CompletionItemKind::FIELD,
            SymbolKind::Enum => CompletionItemKind::ENUM,
            SymbolKind::EnumMember => CompletionItemKind::ENUM_MEMBER,
        },
    }
}

enum KeywordPostfix {
    None,
    Space,
    Parentheses,
    ParenthesesSpace,
}

struct Keyword(&'static str, KeywordPostfix);

fn keywords_to_completion(keywords: &[Keyword]) -> Vec<CompletionItem> {
    keywords
        .iter()
        .map(|keyword| {
            let label = keyword.0.to_owned();
            let (insert_text, insert_text_format) = match keyword.1 {
                KeywordPostfix::None => (None, None),
                KeywordPostfix::Space => (Some(format!("{} ", keyword.0)), None),
                KeywordPostfix::Parentheses => (
                    Some(format!("{}($1)", keyword.0)),
                    Some(InsertTextFormat::SNIPPET),
                ),
                KeywordPostfix::ParenthesesSpace => (
                    Some(format!("{} ($1)", keyword.0)),
                    Some(InsertTextFormat::SNIPPET),
                ),
            };
            CompletionItem {
                label,
                kind: Some(CompletionItemKind::KEYWORD),
                insert_text,
                insert_text_format,
                ..Default::default()
            }
        })
        .collect()
}

fn statement_keywords() -> Vec<CompletionItem> {
    let keywords = [
        Keyword("base", KeywordPostfix::None),
        Keyword("break", KeywordPostfix::None),
        Keyword("catch", KeywordPostfix::ParenthesesSpace),
        Keyword("class", KeywordPostfix::Space),
        Keyword("clone", KeywordPostfix::Space),
        Keyword("const", KeywordPostfix::Space),
        Keyword("continue", KeywordPostfix::None),
        Keyword("delete", KeywordPostfix::Space),
        Keyword("do", KeywordPostfix::None),
        Keyword("enum", KeywordPostfix::Space),
        Keyword("foreach", KeywordPostfix::ParenthesesSpace),
        Keyword("for", KeywordPostfix::ParenthesesSpace),
        Keyword("function", KeywordPostfix::Space),
        Keyword("if", KeywordPostfix::ParenthesesSpace),
        Keyword("local", KeywordPostfix::Space),
        Keyword("rawcall", KeywordPostfix::Parentheses),
        Keyword("resume", KeywordPostfix::Space),
        Keyword("return", KeywordPostfix::None),
        Keyword("switch", KeywordPostfix::ParenthesesSpace),
        Keyword("this", KeywordPostfix::None),
        Keyword("throw", KeywordPostfix::Space),
        Keyword("try", KeywordPostfix::None),
        Keyword("while", KeywordPostfix::ParenthesesSpace),
        Keyword("yield", KeywordPostfix::Space),
    ];

    keywords_to_completion(&keywords)
}

fn expression_keywords() -> Vec<CompletionItem> {
    let keywords = [
        Keyword("base", KeywordPostfix::None),
        Keyword("class", KeywordPostfix::Space),
        Keyword("clone", KeywordPostfix::Space),
        Keyword("delete", KeywordPostfix::Space),
        Keyword("resume", KeywordPostfix::Space),
        Keyword("this", KeywordPostfix::None),
        Keyword("function", KeywordPostfix::Parentheses),
        Keyword("null", KeywordPostfix::None),
        Keyword("false", KeywordPostfix::None),
        Keyword("true", KeywordPostfix::None),
        Keyword("typeof", KeywordPostfix::Space),
        Keyword("__FILE__", KeywordPostfix::None),
        Keyword("__LINE__", KeywordPostfix::None),
    ];

    keywords_to_completion(&keywords)
}

fn completions_flat(offset: TextSize, finished_file: &FinishedFile<'_>) -> Vec<CompletionItem> {
    finished_file
        .symbols_at(offset, true)
        .into_iter()
        .map(|(mut label, id)| {
            let symbol = finished_file.get(id);
            let kind = Some(to_completion_kind(symbol));
            let mut insert_text = None;
            let (insert_text_format, command) =
                modify_if_function(finished_file, symbol, &mut label, &mut insert_text)
                    .map_or((None, None), |(a, b)| (Some(a), Some(b)));

            CompletionItem {
                label,
                kind,
                insert_text,
                command,
                insert_text_format,
                tags: symbol_tags(symbol),
                ..Default::default()
            }
        })
        .collect()
}

fn completions_from_object(
    line_idx: &LineIndex,
    offset: TextSize,
    finished_file: &FinishedFile<'_>,
    scope: ScopeId,
    typ: Type,
    prefix_range: TextRange,
) -> Vec<CompletionItem> {
    finished_file
        .members_of_type(
            typ,
            FindSymbol::BeforeIfInExecutionRange(offset, scope),
            true,
        )
        .into_iter()
        .map(|(mut label, id)| {
            let symbol = finished_file.get(id);
            let kind = Some(to_completion_kind(symbol));
            if can_use_identifier(&label) {
                let mut insert_text = None;
                let (insert_text_format, command) =
                    modify_if_function(finished_file, symbol, &mut label, &mut insert_text)
                        .map_or((None, None), |(a, b)| (Some(a), Some(b)));

                return CompletionItem {
                    label,
                    kind,
                    insert_text,
                    command,
                    insert_text_format,
                    tags: symbol_tags(symbol),
                    ..Default::default()
                };
            }

            let mut insert_text = Some(format!("[\"{label}\"]"));
            let additional_text_edits = Some(vec![TextEdit {
                range: conversions::range(line_idx, prefix_range),
                new_text: String::new(),
            }]);

            let (insert_text_format, command) =
                modify_if_function(finished_file, symbol, &mut label, &mut insert_text)
                    .map_or((None, None), |(a, b)| (Some(a), Some(b)));

            CompletionItem {
                label,
                kind,
                insert_text,
                command,
                insert_text_format,
                additional_text_edits,
                tags: symbol_tags(symbol),
                ..Default::default()
            }
        })
        .collect()
}

fn completions_from_qualified_name(
    offset: TextSize,
    finished_file: &FinishedFile<'_>,
    scope: ScopeId,
    typ: Option<Type>,
) -> Vec<CompletionItem> {
    let all_members = typ.map_or_else(
        || finished_file.symbols_at(offset, false),
        |typ| {
            finished_file.members_of_type(
                typ,
                FindSymbol::BeforeIfInExecutionRange(offset, scope),
                false,
            )
        },
    );

    all_members
        .into_iter()
        .filter_map(|(name, id)| {
            let symbol = finished_file.get(id);
            if !matches!(
                symbol.typ.0,
                Type::Table(_) | Type::Class(_) | Type::Instance(_)
            ) {
                return None;
            }

            Some(CompletionItem {
                label: name,
                kind: Some(to_completion_kind(symbol)),
                ..Default::default()
            })
        })
        .collect()
}

fn completions_from_object_as_string(
    line_idx: &LineIndex,
    offset: TextSize,
    finished_file: &FinishedFile<'_>,
    scope: ScopeId,
    typ: Type,
    replace_range: TextRange,
) -> Vec<CompletionItem> {
    finished_file
        .members_of_type(
            typ,
            FindSymbol::BeforeIfInExecutionRange(offset, scope),
            true,
        )
        .into_iter()
        .map(|(mut label, id)| {
            let symbol = finished_file.get(id);
            let kind = Some(to_completion_kind(symbol));

            let mut insert_text = Some(format!("{label}\"]"));
            let (insert_text_format, command) =
                modify_if_function(finished_file, symbol, &mut label, &mut insert_text)
                    .map_or((None, None), |(a, b)| (Some(a), Some(b)));

            let text_edit = Some(CompletionTextEdit::Edit(TextEdit {
                range: conversions::range(line_idx, replace_range),
                new_text: insert_text.expect("modify_if_function cannot convert Some to None"),
            }));

            CompletionItem {
                label,
                kind,
                text_edit,
                command,
                insert_text_format,
                tags: symbol_tags(symbol),
                ..Default::default()
            }
        })
        .collect()
}

fn completions_root(
    offset: TextSize,
    finished_file: &FinishedFile<'_>,
    scope: ScopeId,
) -> Vec<CompletionItem> {
    finished_file
        .members_of_table(
            finished_file.root_table(),
            FindSymbol::BeforeIfInExecutionRange(offset, scope),
            ImportMembers::Root,
        )
        .into_iter()
        .map(|(mut label, id)| {
            let symbol = finished_file.get(id);
            let kind = Some(to_completion_kind(symbol));
            let mut insert_text = None;
            let (insert_text_format, command) =
                modify_if_function(finished_file, symbol, &mut label, &mut insert_text)
                    .map_or((None, None), |(a, b)| (Some(a), Some(b)));

            CompletionItem {
                label,
                kind,
                insert_text,
                command,
                insert_text_format,
                tags: symbol_tags(symbol),
                ..Default::default()
            }
        })
        .collect()
}

fn completion_doc_tag(
    line_idx: &LineIndex,
    replace_range: Option<TextRange>,
) -> Vec<CompletionItem> {
    let tags = [
        "@param ",
        "@returns",
        "@throws",
        "@yields",
        "@type",
        "@varargs",
        "@deprecated",
        "@hide",
        "@native",
        "@entity",
        "@const",
        "@input",
    ];
    let range = replace_range.map(|r| conversions::range(line_idx, r));
    tags.into_iter()
        .map(|name| CompletionItem {
            label: name.to_owned(),
            kind: Some(CompletionItemKind::KEYWORD),
            text_edit: range.map(|r| {
                CompletionTextEdit::Edit(TextEdit {
                    range: r,
                    new_text: name.to_owned(),
                })
            }),
            ..Default::default()
        })
        .collect()
}

fn completions_doc_type(offset: TextSize, finished_file: &FinishedFile<'_>) -> Vec<CompletionItem> {
    let tags = [
        "any",
        "integer",
        "float",
        "string",
        "bool",
        "table",
        "array",
        "class",
        "instance",
        "function",
        "null",
        "generator",
        "thread",
        "weakref",
    ];
    let symbols = finished_file.symbols_at(offset, true);

    tags.into_iter()
        .map(|name| CompletionItem {
            label: name.to_owned(),
            kind: Some(CompletionItemKind::KEYWORD),
            ..Default::default()
        })
        .chain(symbols.into_iter().filter_map(|(name, id)| {
            if !matches!(finished_file.get(id).typ.0, Type::Class(_)) {
                return None;
            }
            Some(CompletionItem {
                label: name,
                kind: Some(CompletionItemKind::CLASS),
                ..Default::default()
            })
        }))
        .collect()
}

fn completions_doc_param_names(
    id: FunctionId,
    finished_file: &FinishedFile,
) -> Vec<CompletionItem> {
    finished_file
        .get(id)
        .params
        .iter()
        .map(|id| {
            let label = finished_file.get(*id).name.clone();
            CompletionItem {
                label,
                kind: Some(CompletionItemKind::VARIABLE),
                ..Default::default()
            }
        })
        .collect()
}

fn completion_doc_auto_generated(
    line_idx: &LineIndex,
    finished_file: &FinishedFile<'_>,
    typ: Type,
    replace_range: TextRange,
) -> Vec<CompletionItem> {
    #[allow(clippy::literal_string_with_formatting_args)]
    let text = match typ {
        Type::Function(Some(id)) => {
            let mut text = "/**\n * ${1:Description}".to_owned();
            let mut last_index = 1;
            for param in &finished_file.get(id).params {
                last_index += 1;

                let symbol = finished_file.get(*param);

                let typ = match symbol.typ.0 {
                    Type::Unknown | Type::Null => Type::Any,
                    _ => symbol.typ.0,
                };

                let name = &symbol.name;

                let _ = write!(
                    text,
                    "\n * @param {{${{{}:{}}}}} {}",
                    last_index,
                    finished_file.type_to_string(typ),
                    name
                );
            }

            if let Some(ret) = finished_file.get(id).ret
                && ret.0 != Type::Null
            {
                last_index += 1;

                let typ = match ret.0 {
                    Type::Unknown => Type::Any,
                    _ => ret.0,
                };

                let _ = write!(
                    text,
                    "\n * @returns {{${{{}:{}}}}}",
                    last_index,
                    finished_file.type_to_string(typ)
                );
            }

            if let Some(throws) = finished_file.get(id).throws {
                last_index += 1;

                let typ = match throws.0 {
                    Type::Unknown => Type::Any,
                    _ => throws.0,
                };

                let _ = write!(
                    text,
                    "\n * @throws {{${{{}:{}}}}}",
                    last_index,
                    finished_file.type_to_string(typ)
                );
            }

            if let Some(yields) = finished_file.get(id).yields {
                let typ = match yields.0 {
                    Type::Unknown => Type::Any,
                    _ => yields.0,
                };

                let _ = write!(
                    text,
                    "\n * @yields {{${{{}:{}}}}}",
                    last_index + 1,
                    finished_file.type_to_string(typ)
                );
            }

            let _ = write!(text, "\n */");
            text
        }
        _ => {
            format!(
                "/**\n * ${{1:Description}}\n * @type {{${{2:{}}}}}\n */",
                finished_file.type_to_string(typ),
            )
        }
    };

    let additional_text_edits = Some(vec![TextEdit {
        range: conversions::range(line_idx, replace_range),
        new_text: String::new(),
    }]);

    vec![CompletionItem {
        label: "Autogenerated Doc Comment ...".to_owned(),
        kind: Some(CompletionItemKind::KEYWORD),
        insert_text: Some(text),
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        additional_text_edits,
        ..Default::default()
    }]
}
